

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=mydb
    ports:
      - "3307:3306"
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    links:
      - mysql  