

services:
  mysql:
    image: mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
    ports:
      - "$DB_LOCAL_PORT:$DB_DOCKER_PORT"
  app:
    build: .
    ports:
      - "$APP_LOCAL_PORT:$APP_DOCKER_PORT"
    depends_on:
      - mysql
    links:
      - mysql  